blending_modes = {
    "Normal": "normal",
    "Dissolve": "dissolve",
    "Darken": "darken",
    "Multiply": "multiply",
    "Burn": "burn",
    "Linear Burn": "linear_burn",
    "Darker Color": "darker color",
    "Lighten": "lighten",
    "Screen": "screen",
    "Color Dodge": "dodge",
    "Linear Dodge": "linear_dodge",
    "Lighter Color": "lighter color",
    "Overlay": "overlay",
    "Soft Light": "soft_light",
    "Hard Light": "hard_light",
    "Vivid Light": "vivid_light",
    "Linear Light": "linear light",
    "Pin Light": "pin_light",
    "Hard Mix": "hard mix",
    "Difference": "diff",
    "Exclusion": "exclusion",
    "Divide": "divide",
    "Hue": "hue",
    "Saturation": "saturation",
    "Color": "color",
    "Luminosity": "luminosity_sai",
    }